# Generated by Django 4.2.8 on 2023-12-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_name_product_p_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Enter the product stock'),
            preserve_default=False,
        ),
    ]
